# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vtn_disp_entrada_ingresar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vtn_disp_entrada_ingresar(object):
    def setupUi(self, vtn_disp_entrada_ingresar):
        vtn_disp_entrada_ingresar.setObjectName("vtn_disp_entrada_ingresar")
        vtn_disp_entrada_ingresar.resize(480, 285)
        self.centralwidget = QtWidgets.QWidget(vtn_disp_entrada_ingresar)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_disp_entrada = QtWidgets.QLabel(self.centralwidget)
        self.lbl_disp_entrada.setGeometry(QtCore.QRect(16, 22, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_disp_entrada.setFont(font)
        self.lbl_disp_entrada.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_disp_entrada.setObjectName("lbl_disp_entrada")
        self.lbl_tipo_dispositivo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tipo_dispositivo.setGeometry(QtCore.QRect(70, 60, 111, 20))
        self.lbl_tipo_dispositivo.setObjectName("lbl_tipo_dispositivo")
        self.lbl_marca = QtWidgets.QLabel(self.centralwidget)
        self.lbl_marca.setGeometry(QtCore.QRect(120, 100, 47, 13))
        self.lbl_marca.setObjectName("lbl_marca")
        self.lbl_tipo_entrada = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tipo_entrada.setGeometry(QtCore.QRect(66, 140, 91, 20))
        self.lbl_tipo_entrada.setObjectName("lbl_tipo_entrada")
        self.cb_tipo_dispositivo = QtWidgets.QComboBox(self.centralwidget)
        self.cb_tipo_dispositivo.setGeometry(QtCore.QRect(190, 60, 151, 22))
        self.cb_tipo_dispositivo.setObjectName("cb_tipo_dispositivo")
        self.cb_tipo_dispositivo.addItem("")
        self.cb_tipo_dispositivo.addItem("")
        self.txt_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_marca.setGeometry(QtCore.QRect(190, 100, 151, 20))
        self.txt_marca.setObjectName("txt_marca")
        self.cb_tipo_entrada = QtWidgets.QComboBox(self.centralwidget)
        self.cb_tipo_entrada.setGeometry(QtCore.QRect(190, 140, 151, 22))
        self.cb_tipo_entrada.setObjectName("cb_tipo_entrada")
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(200, 210, 75, 23))
        self.btn_guardar.setObjectName("btn_guardar")
        vtn_disp_entrada_ingresar.setCentralWidget(self.centralwidget)
        self.stb_estado = QtWidgets.QStatusBar(vtn_disp_entrada_ingresar)
        self.stb_estado.setObjectName("stb_estado")
        vtn_disp_entrada_ingresar.setStatusBar(self.stb_estado)

        self.retranslateUi(vtn_disp_entrada_ingresar)
        QtCore.QMetaObject.connectSlotsByName(vtn_disp_entrada_ingresar)

    def retranslateUi(self, vtn_disp_entrada_ingresar):
        _translate = QtCore.QCoreApplication.translate
        vtn_disp_entrada_ingresar.setWindowTitle(_translate("vtn_disp_entrada_ingresar", "Ingreso de Dispositivo"))
        self.lbl_disp_entrada.setText(_translate("vtn_disp_entrada_ingresar", "Ingreso Dispositivo de Entrada"))
        self.lbl_tipo_dispositivo.setText(_translate("vtn_disp_entrada_ingresar", "Escoja el Dispositivo:"))
        self.lbl_marca.setText(_translate("vtn_disp_entrada_ingresar", "Marca:"))
        self.lbl_tipo_entrada.setText(_translate("vtn_disp_entrada_ingresar", "Tipo de Entrada"))
        self.cb_tipo_dispositivo.setItemText(0, _translate("vtn_disp_entrada_ingresar", "Ratón"))
        self.cb_tipo_dispositivo.setItemText(1, _translate("vtn_disp_entrada_ingresar", "Teclado"))
        self.btn_guardar.setText(_translate("vtn_disp_entrada_ingresar", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vtn_disp_entrada_ingresar = QtWidgets.QMainWindow()
    ui = Ui_vtn_disp_entrada_ingresar()
    ui.setupUi(vtn_disp_entrada_ingresar)
    vtn_disp_entrada_ingresar.show()
    sys.exit(app.exec_())
