# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vtn_raton_ingresar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vtn_raton_ingresar(object):
    def setupUi(self, vtn_raton_ingresar):
        vtn_raton_ingresar.setObjectName("vtn_raton_ingresar")
        vtn_raton_ingresar.resize(473, 214)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(vtn_raton_ingresar.sizePolicy().hasHeightForWidth())
        vtn_raton_ingresar.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(vtn_raton_ingresar)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_ingreso_raton = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ingreso_raton.setGeometry(QtCore.QRect(6, 2, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ingreso_raton.setFont(font)
        self.lbl_ingreso_raton.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ingreso_raton.setObjectName("lbl_ingreso_raton")
        self.lbl_marca = QtWidgets.QLabel(self.centralwidget)
        self.lbl_marca.setGeometry(QtCore.QRect(120, 50, 71, 16))
        self.lbl_marca.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_marca.setObjectName("lbl_marca")
        self.lbl_entrada = QtWidgets.QLabel(self.centralwidget)
        self.lbl_entrada.setGeometry(QtCore.QRect(120, 80, 71, 16))
        self.lbl_entrada.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_entrada.setObjectName("lbl_entrada")
        self.txt_marca = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_marca.setGeometry(QtCore.QRect(210, 50, 131, 20))
        self.txt_marca.setObjectName("txt_marca")
        self.txt_entrada = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_entrada.setGeometry(QtCore.QRect(210, 80, 131, 20))
        self.txt_entrada.setObjectName("txt_entrada")
        self.btn_raton_ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_raton_ingresar.setGeometry(QtCore.QRect(200, 150, 75, 23))
        self.btn_raton_ingresar.setObjectName("btn_raton_ingresar")
        self.txt_cantidad_botones = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cantidad_botones.setGeometry(QtCore.QRect(210, 110, 131, 20))
        self.txt_cantidad_botones.setObjectName("txt_cantidad_botones")
        self.lbl_entrada_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_entrada_2.setGeometry(QtCore.QRect(90, 110, 101, 20))
        self.lbl_entrada_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_entrada_2.setObjectName("lbl_entrada_2")
        vtn_raton_ingresar.setCentralWidget(self.centralwidget)
        self.stb_estado = QtWidgets.QStatusBar(vtn_raton_ingresar)
        self.stb_estado.setObjectName("stb_estado")
        vtn_raton_ingresar.setStatusBar(self.stb_estado)

        self.retranslateUi(vtn_raton_ingresar)
        QtCore.QMetaObject.connectSlotsByName(vtn_raton_ingresar)

    def retranslateUi(self, vtn_raton_ingresar):
        _translate = QtCore.QCoreApplication.translate
        vtn_raton_ingresar.setWindowTitle(_translate("vtn_raton_ingresar", "Raton"))
        self.lbl_ingreso_raton.setText(_translate("vtn_raton_ingresar", "Ingresar Ratón"))
        self.lbl_marca.setText(_translate("vtn_raton_ingresar", "Marca:"))
        self.lbl_entrada.setText(_translate("vtn_raton_ingresar", "Tipo Entrada:"))
        self.btn_raton_ingresar.setText(_translate("vtn_raton_ingresar", "Ingresar"))
        self.lbl_entrada_2.setText(_translate("vtn_raton_ingresar", "Cantidad Botones"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vtn_raton_ingresar = QtWidgets.QMainWindow()
    ui = Ui_vtn_raton_ingresar()
    ui.setupUi(vtn_raton_ingresar)
    vtn_raton_ingresar.show()
    sys.exit(app.exec_())
