# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vtn_persona.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vtn_Persona(object):
    def setupUi(self, vtn_Persona):
        vtn_Persona.setObjectName("vtn_Persona")
        vtn_Persona.resize(644, 323)
        self.centralwidget = QtWidgets.QWidget(vtn_Persona)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nombre.setGeometry(QtCore.QRect(320, 20, 113, 20))
        self.txt_nombre.setMaxLength(50)
        self.txt_nombre.setObjectName("txt_nombre")
        self.txt_cedula = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cedula.setGeometry(QtCore.QRect(320, 90, 113, 20))
        self.txt_cedula.setMaxLength(10)
        self.txt_cedula.setObjectName("txt_cedula")
        self.txt_email = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(320, 130, 113, 20))
        self.txt_email.setMaxLength(100)
        self.txt_email.setObjectName("txt_email")
        self.txt_telefono = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_telefono.setGeometry(QtCore.QRect(320, 170, 113, 20))
        self.txt_telefono.setMaxLength(10)
        self.txt_telefono.setObjectName("txt_telefono")
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(280, 240, 75, 23))
        self.btn_guardar.setObjectName("btn_guardar")
        self.lbl_nombre = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nombre.setGeometry(QtCore.QRect(210, 20, 47, 13))
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lbl_cedula = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cedula.setGeometry(QtCore.QRect(210, 90, 47, 13))
        self.lbl_cedula.setObjectName("lbl_cedula")
        self.lbl_email = QtWidgets.QLabel(self.centralwidget)
        self.lbl_email.setGeometry(QtCore.QRect(210, 130, 47, 13))
        self.lbl_email.setObjectName("lbl_email")
        self.lbl_telefono = QtWidgets.QLabel(self.centralwidget)
        self.lbl_telefono.setGeometry(QtCore.QRect(210, 170, 47, 13))
        self.lbl_telefono.setObjectName("lbl_telefono")
        self.lbl_apellido = QtWidgets.QLabel(self.centralwidget)
        self.lbl_apellido.setGeometry(QtCore.QRect(200, 60, 47, 13))
        self.lbl_apellido.setObjectName("lbl_apellido")
        self.txt_apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_apellido.setGeometry(QtCore.QRect(320, 50, 113, 20))
        self.txt_apellido.setObjectName("txt_apellido")
        vtn_Persona.setCentralWidget(self.centralwidget)
        self.stb_estado = QtWidgets.QStatusBar(vtn_Persona)
        self.stb_estado.setObjectName("stb_estado")
        vtn_Persona.setStatusBar(self.stb_estado)

        self.retranslateUi(vtn_Persona)
        QtCore.QMetaObject.connectSlotsByName(vtn_Persona)

    def retranslateUi(self, vtn_Persona):
        _translate = QtCore.QCoreApplication.translate
        vtn_Persona.setWindowTitle(_translate("vtn_Persona", "Persona"))
        self.btn_guardar.setText(_translate("vtn_Persona", "Guardar"))
        self.lbl_nombre.setText(_translate("vtn_Persona", "Nombre"))
        self.lbl_cedula.setText(_translate("vtn_Persona", "Cedula"))
        self.lbl_email.setText(_translate("vtn_Persona", "Email"))
        self.lbl_telefono.setText(_translate("vtn_Persona", "Telefono"))
        self.lbl_apellido.setText(_translate("vtn_Persona", "Apellido:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vtn_Persona = QtWidgets.QMainWindow()
    ui = Ui_vtn_Persona()
    ui.setupUi(vtn_Persona)
    vtn_Persona.show()
    sys.exit(app.exec_())
