# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vtn_persona_modificar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vtn_Persona_modificar(object):
    def setupUi(self, vtn_Persona_modificar):
        vtn_Persona_modificar.setObjectName("vtn_Persona_modificar")
        vtn_Persona_modificar.resize(767, 323)
        self.centralwidget = QtWidgets.QWidget(vtn_Persona_modificar)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nombre.setGeometry(QtCore.QRect(320, 60, 113, 20))
        self.txt_nombre.setMaxLength(50)
        self.txt_nombre.setObjectName("txt_nombre")
        self.txt_cedula = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cedula.setGeometry(QtCore.QRect(320, 130, 113, 20))
        self.txt_cedula.setMaxLength(10)
        self.txt_cedula.setObjectName("txt_cedula")
        self.txt_email = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(320, 170, 113, 20))
        self.txt_email.setMaxLength(100)
        self.txt_email.setObjectName("txt_email")
        self.txt_telefono = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_telefono.setGeometry(QtCore.QRect(320, 210, 113, 20))
        self.txt_telefono.setMaxLength(10)
        self.txt_telefono.setObjectName("txt_telefono")
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(280, 280, 75, 23))
        self.btn_guardar.setObjectName("btn_guardar")
        self.lbl_nombre = QtWidgets.QLabel(self.centralwidget)
        self.lbl_nombre.setGeometry(QtCore.QRect(210, 60, 47, 13))
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lbl_cedula = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cedula.setGeometry(QtCore.QRect(210, 130, 47, 13))
        self.lbl_cedula.setObjectName("lbl_cedula")
        self.lbl_email = QtWidgets.QLabel(self.centralwidget)
        self.lbl_email.setGeometry(QtCore.QRect(210, 170, 47, 13))
        self.lbl_email.setObjectName("lbl_email")
        self.lbl_telefono = QtWidgets.QLabel(self.centralwidget)
        self.lbl_telefono.setGeometry(QtCore.QRect(210, 210, 47, 13))
        self.lbl_telefono.setObjectName("lbl_telefono")
        self.lbl_apellido = QtWidgets.QLabel(self.centralwidget)
        self.lbl_apellido.setGeometry(QtCore.QRect(200, 100, 47, 13))
        self.lbl_apellido.setObjectName("lbl_apellido")
        self.txt_apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_apellido.setGeometry(QtCore.QRect(320, 90, 113, 20))
        self.txt_apellido.setObjectName("txt_apellido")
        self.lbl_buscar_cedula = QtWidgets.QLabel(self.centralwidget)
        self.lbl_buscar_cedula.setGeometry(QtCore.QRect(136, 12, 111, 21))
        self.lbl_buscar_cedula.setObjectName("lbl_buscar_cedula")
        self.txt_buscar_cedula = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_buscar_cedula.setGeometry(QtCore.QRect(320, 10, 113, 20))
        self.txt_buscar_cedula.setObjectName("txt_buscar_cedula")
        self.btn_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_buscar.setGeometry(QtCore.QRect(480, 10, 75, 23))
        self.btn_buscar.setObjectName("btn_buscar")
        self.btn_eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eliminar.setGeometry(QtCore.QRect(610, 10, 75, 23))
        self.btn_eliminar.setObjectName("btn_eliminar")
        vtn_Persona_modificar.setCentralWidget(self.centralwidget)
        self.stb_estado = QtWidgets.QStatusBar(vtn_Persona_modificar)
        self.stb_estado.setObjectName("stb_estado")
        vtn_Persona_modificar.setStatusBar(self.stb_estado)

        self.retranslateUi(vtn_Persona_modificar)
        QtCore.QMetaObject.connectSlotsByName(vtn_Persona_modificar)

    def retranslateUi(self, vtn_Persona_modificar):
        _translate = QtCore.QCoreApplication.translate
        vtn_Persona_modificar.setWindowTitle(_translate("vtn_Persona_modificar", "Persona"))
        self.btn_guardar.setText(_translate("vtn_Persona_modificar", "Guardar"))
        self.lbl_nombre.setText(_translate("vtn_Persona_modificar", "Nombre"))
        self.lbl_cedula.setText(_translate("vtn_Persona_modificar", "Cedula"))
        self.lbl_email.setText(_translate("vtn_Persona_modificar", "Email"))
        self.lbl_telefono.setText(_translate("vtn_Persona_modificar", "Telefono"))
        self.lbl_apellido.setText(_translate("vtn_Persona_modificar", "Apellido:"))
        self.lbl_buscar_cedula.setText(_translate("vtn_Persona_modificar", "Buscar por cedula"))
        self.btn_buscar.setText(_translate("vtn_Persona_modificar", "Buscar"))
        self.btn_eliminar.setText(_translate("vtn_Persona_modificar", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vtn_Persona_modificar = QtWidgets.QMainWindow()
    ui = Ui_vtn_Persona_modificar()
    ui.setupUi(vtn_Persona_modificar)
    vtn_Persona_modificar.show()
    sys.exit(app.exec_())
