# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vtn_computador_ingresar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vtn_computador(object):
    def setupUi(self, vtn_computador):
        vtn_computador.setObjectName("vtn_computador")
        vtn_computador.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(vtn_computador)
        self.centralwidget.setObjectName("centralwidget")
        self.tb_ratones = QtWidgets.QTableWidget(self.centralwidget)
        self.tb_ratones.setGeometry(QtCore.QRect(20, 160, 421, 111))
        self.tb_ratones.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tb_ratones.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tb_ratones.setObjectName("tb_ratones")
        self.tb_ratones.setColumnCount(4)
        self.tb_ratones.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_ratones.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_ratones.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_ratones.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_ratones.setHorizontalHeaderItem(3, item)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 350, 421, 111))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(620, 290, 75, 23))
        self.btn_guardar.setObjectName("btn_guardar")
        self.txt_descripcion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_descripcion.setGeometry(QtCore.QRect(40, 50, 113, 20))
        self.txt_descripcion.setObjectName("txt_descripcion")
        vtn_computador.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vtn_computador)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        vtn_computador.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(vtn_computador)
        self.statusbar.setObjectName("statusbar")
        vtn_computador.setStatusBar(self.statusbar)

        self.retranslateUi(vtn_computador)
        QtCore.QMetaObject.connectSlotsByName(vtn_computador)

    def retranslateUi(self, vtn_computador):
        _translate = QtCore.QCoreApplication.translate
        vtn_computador.setWindowTitle(_translate("vtn_computador", "MainWindow"))
        item = self.tb_ratones.horizontalHeaderItem(0)
        item.setText(_translate("vtn_computador", "Id"))
        item = self.tb_ratones.horizontalHeaderItem(1)
        item.setText(_translate("vtn_computador", "Marca"))
        item = self.tb_ratones.horizontalHeaderItem(2)
        item.setText(_translate("vtn_computador", "Entrada"))
        item = self.tb_ratones.horizontalHeaderItem(3)
        item.setText(_translate("vtn_computador", "Botones"))
        self.btn_guardar.setText(_translate("vtn_computador", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vtn_computador = QtWidgets.QMainWindow()
    ui = Ui_vtn_computador()
    ui.setupUi(vtn_computador)
    vtn_computador.show()
    sys.exit(app.exec_())
